### ISSUE TITLE
Images for README.md

### ISSUE THREAD

**Issue by nunofachada** [fakenmc/perfandpubtools#1]
![arch](https://cloud.githubusercontent.com/assets/3018963/12206544/74c5ac38-b639-11e5-87c2-fc65e6bf8875.png)

![ex4 1 5_1](https://cloud.githubusercontent.com/assets/3018963/14692286/0d3a86ae-074e-11e6-95c7-270c35ce04de.png)
![ex4 1 5_2](https://cloud.githubusercontent.com/assets/3018963/14692287/0d40bbbe-074e-11e6-8d2c-c7d245b7cbd1.png)
![ex4 1 6_1](https://cloud.githubusercontent.com/assets/3018963/14692288/0d42faaa-074e-11e6-8eea-94dde29d3e5d.png)
![ex4 1 6_2](https://cloud.githubusercontent.com/assets/3018963/14692289/0d47a0c8-074e-11e6-928e-6f5fd8ed6528.png)
![ex4 1 7_1](https://cloud.githubusercontent.com/assets/3018963/14688435/6bf1c108-073a-11e6-8cc8-258ea48f04a5.png)
![ex4 1 7_2](https://cloud.githubusercontent.com/assets/3018963/14715181/cfda758e-07df-11e6-8013-10364091773b.png)
![ex4 1 8_1](https://cloud.githubusercontent.com/assets/3018963/14703285/15d2f75c-07a7-11e6-8f0f-bd5d83bb5774.png)
![ex4 1 8_2](https://cloud.githubusercontent.com/assets/3018963/14703318/399654a4-07a7-11e6-8828-a84ce171ff5a.png)
![ex4 1 8_3](https://cloud.githubusercontent.com/assets/3018963/14715383/83ffe3e6-07e0-11e6-8bd0-33898a6c5159.png)
![ex4 1 8_4](https://cloud.githubusercontent.com/assets/3018963/14715384/84054192-07e0-11e6-9da1-88bb990f4588.png)
![ex4 1 9_1](https://cloud.githubusercontent.com/assets/3018963/14691633/367ade1e-074a-11e6-9935-40f5e9f49763.png)
![ex4 1 9_2](https://cloud.githubusercontent.com/assets/3018963/14691634/3681a91a-074a-11e6-818c-498c68d2f8f0.png)
![ex4 1 10](https://cloud.githubusercontent.com/assets/3018963/14692331/502d8646-074e-11e6-9cc9-fb7fe8fd9cb5.png)
![ex4 1 11_1](https://cloud.githubusercontent.com/assets/3018963/14691914/c9e8deca-074b-11e6-8386-d15ca2f5f773.png)
![ex4 1 11_2](https://cloud.githubusercontent.com/assets/3018963/14691915/ca03003e-074b-11e6-85fd-155e7cf2314a.png)
![ex4 1 12](https://cloud.githubusercontent.com/assets/3018963/14691916/ca160698-074b-11e6-9598-9bd2ce6f6a7e.png)
![ex4 1 13](https://user-images.githubusercontent.com/3018963/29131676-882ab804-7d25-11e7-846b-3df6c3fc39f9.png)

![ex4 2 6_1](https://cloud.githubusercontent.com/assets/3018963/14692567/fc5a2004-074f-11e6-91d1-e82b5260f74c.png)
![ex4 2 6_2](https://cloud.githubusercontent.com/assets/3018963/14692568/fc5e537c-074f-11e6-81df-aecfda2c2618.png)
![ex4 2 7](https://cloud.githubusercontent.com/assets/3018963/14692605/3660f0a2-0750-11e6-9d5d-375a1b5777fe.png)
![ex4 2 8_1](https://cloud.githubusercontent.com/assets/3018963/14692693/e6b122ce-0750-11e6-973d-1742d81974ed.png)
![ex4 2 8_2](https://cloud.githubusercontent.com/assets/3018963/14715792/2214f98a-07e2-11e6-807f-cd37b88533d8.png)
![ex4 2 9_1](https://cloud.githubusercontent.com/assets/3018963/14706004/308d5576-07b4-11e6-8509-506cb4af5733.png)
![ex4 2 9_2](https://cloud.githubusercontent.com/assets/3018963/14706005/30a50b30-07b4-11e6-963c-1b20102b1cbb.png)
![ex4 2 10](https://cloud.githubusercontent.com/assets/3018963/14692845/fdb21130-0751-11e6-9e75-428f92e3b59b.png)
![ex4 2 11](https://cloud.githubusercontent.com/assets/3018963/14692932/aba1f486-0752-11e6-8dd9-b5d673dc50ce.png)
![ex4 2 13_1](https://cloud.githubusercontent.com/assets/3018963/14706270/8e7c0e9c-07b5-11e6-8fe8-cbd24c184cec.png)
![ex4 2 13_2](https://cloud.githubusercontent.com/assets/3018963/14706271/8e7c4fce-07b5-11e6-8ed5-09853541b4a4.png)
![ex4 2 14](https://cloud.githubusercontent.com/assets/3018963/14706361/f6f1c8cc-07b5-11e6-9c7d-87af968ac115.png)
![ex4 2 15](https://cloud.githubusercontent.com/assets/3018963/14706360/f6f17d18-07b5-11e6-926f-2314f9d59206.png)

![arch_v2](https://user-images.githubusercontent.com/3018963/27658231-3aaa5246-5c47-11e7-8cf7-05c212dae25c.png)

![architecture](https://user-images.githubusercontent.com/3018963/28936022-47455688-787e-11e7-8ced-242bb6104f52.png)

![ex_pw_table](https://user-images.githubusercontent.com/3018963/29043497-57cb5e52-7bb3-11e7-990a-7feb5db55726.png)

**Comment by fakenmc** [comment]
Data for "Performance analysis of sorting algorithms" examples:
[sorttest_c.zip](https://github.com/fakenmc/perfandpubtools/files/83777/sorttest_c.zip)

**Comment by nunofachada** [comment]
Data for "Performance analysis of sorting algorithms" examples:
[sorttest_c.zip](https://github.com/fakenmc/perfandpubtools/files/83822/sorttest_c.zip)
